version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: chat-p2p-postgres
    env_file: .env
    environment:
      POSTGRES_USER: "${SERVER_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${SERVER_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${SERVER_POSTGRES_DATABASE}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chatp2p-server-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: chat-p2p-pgadmin
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - chatp2p-server-network

networks:
  chatp2p-server-network:
    driver: bridge

volumes:
  postgres_data:
